### ISSUE TITLE
No data pulled for Tower Hamlets

### ISSUE THREAD

**Issue by TomAnks** [robmarkcole/London-air-quality-HASS#2]
Firstly, thanks for this useful add-on! I am just getting started with HA and am trying to set this up.

Here is what I have added to my configuration.yaml

```
#London Air Quality sensor integration
sensor:
  - platform: london_air
    locations:
      - Tower Hamlets
template:
  - sensor:
    - name: "Updated"
      state: "{{ state_attr('sensor.tower_hamlets', 'updated') }}"
    - name: "Carbon Monoxide"
      state: "{{ state_attr('sensor.tower_hamlets', 'data')[0].pollutants[0].summary }}"
    - name: "Nitrogen Dioxide"
      state: "{{ state_attr('sensor.tower_hamlets', 'data')[0].pollutants[1].summary }}"
    - name: "Ozone"
      state: "{{ state_attr('sensor.tower_hamlets', 'data')[0].pollutants[2].summary }}"
    - name: "PM10 Particulate"
      state: "{{ state_attr('sensor.tower_hamlets', 'data')[0].pollutants[3].summary }}"
    - name: "PM2.5 Particulate"
      state: "{{ state_attr('sensor.tower_hamlets', 'data')[0].pollutants[4].summary }}"
    - name: "Sulphur Dioxide"
      state: "{{ state_attr('sensor.tower_hamlets', 'data')[0].pollutants[5].summary }}"
```

The sensors appear to have updated at 10am this morning, but I am still seeing 'Unavailable' for most of the sensors.

![image](https://github.com/robmarkcole/London-air-quality-HASS/assets/26800901/5f7e855e-12af-49e6-baed-14699c42fcc1)

Any idea what might be going wrong here? Is Tower Hamlets one of the 4 boroughs that do not have data available mentioned in the Github description?
