### ISSUE TITLE
Unclear how to configure

### ISSUE THREAD

**Issue by jeremyquinn** [robmarkcole/London-air-quality-HASS#3]
I am struggling to use this integration and the documentation is unclear.

1. I have the integration to my main `configuration.yaml` : 
```
sensor:
  - platform: london_air
    locations:
      - Lambeth
```
2. I have the following expressions working in the Developer Tools - Template Editor
```
{{ states("sensor.lambeth") }}
{{ state_attr("sensor.lambeth", "updated") }} 
{{ state_attr('sensor.lambeth', 'data')[0].pollutants[0].summary }}
{{ state_attr('sensor.lambeth', 'data')[0].pollutants[1].summary }}
{{ state_attr('sensor.lambeth', 'data')[0].pollutants[2].summary }}

```
Which output:
```
Low
2024-06-16 14:00:00
NO2 is Low
PM10 is Low
PM25 is Low

```
3. I tried adding template sensors in `configuration.yaml` like this:
```
template:
  sensor:
    - name: Lambeth NO2
         unique_id: "lambeth_pollution_no2"
         state_class: measurement
         device_class: nitrous_oxide
         state: "{{ state_attr('sensor.lambeth', 'data')[0].pollutants[0].summary }}"
```
I did this with each of the values above, they would either display “Unknown” or “Unavailable”.

4. I tried setting up the values as Templates in Helpers and get the same results.

Could we have better samples and instructions please?
